apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossip-testing
  labels:
    app: gossip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gossip
  template:
    metadata:
      labels:
        app: gossip
    spec:
      containers:
        - image: gcr.io/cedi/gossip-experiments:latest
          name: gossip
          cmd: "/gossip"
          args:
            - memberlist
            - join
            - --config
            - lan
            - --name
            - node3
            - --port
            - 7948
            - "gossip.gossip.svc.cluster.local:7946"
          ports:
            - containerPort: 7946
              name: http
