apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossip-testing
  labels:
    app: gossip
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gossip
  template:
    metadata:
      labels:
        app: gossip
    spec:
      containers:
        - image: ghcr.io/cedi/gossip-experiment:main
          name: gossip
          command:
            - "/gossip"
          args:
            - "memberlist"
            - "join"
            - "--config"
            - "lan"
            - "--port"
            - "7946"
            - "gossip.gossip.svc.cluster.local:7946"
          ports:
            - containerPort: 7946
              name: http
